#!/bin/bash
set -exu

# shellcheck disable=SC1091
source cf-deployment-concourse-tasks/shared-functions

function bosh_delete_all_deployments() {
    local deployments
    deployments=$(bosh deployments --json | jq -r '.Tables[].Rows[].name')

    for deployment in ${deployments}; do
      if [ -n "${deployment}" ]; then
        "$DEPLOYMENT_NAME" = "${deployment}"
        echo "Deleting deployment: ${DEPLOYMENT_NAME}"
        bosh_delete_deployment()
      fi
    done   
}

function check_delete_deployment_params() {
  if [ -z "$DEPLOYMENT_NAME" ]; then
    echo "DEPLOYMENT_NAME has not been set"
    exit 1
  fi
}

function bosh_delete_deployment() {
  local force_flag=""

  if [ "$IGNORE_ERRORS" = true ]; then
    force_flag="--force"
  fi

  bosh \
    -n \
    delete-deployment -d ${DEPLOYMENT_NAME} \
    ${force_flag}
}

function main() {
  setup_bosh_env_vars
  if [ "$DELETE_ALL_DEPLOYMENTS" = true ]; then
    bosh_delete_all_deployments
  else
    check_delete_deployment_params
    bosh_delete_deployment
  fi
}

main
